---
- name: create repo for certbot
  copy:
    dest: /etc/apt/sources.list.d/stretch-backports.list
    content: 'deb http://ftp.debian.org/debian stretch-backports main'

- name: apt update
  apt: update_cache=yes upgrade=no cache_valid_time=1800

- name: install nginx packages
  apt: pkg={{ item }} state=latest
  with_items:
    - nginx
    - php7.0-fpm
    - python-certbot-nginx

- name: modify nginx config
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

#- name: register certbot
#  command: certbot --authenticator nginx --installer nginx --domains $DOMAIN --renew-by-default --agree-tos --no-eff-email -m "$EMAIL" --no-redirect

- name: restart nginx
  action: service name=nginx state=restarted enabled=yes

- name: restart php
  action: service name=php7.0-fpm state=restarted enabled=yes

