#################on commandline####################
#as user
ansible -m shell -a 'free -m' [HOSTGRUPPE]
#change to root
ansible --su --su-user=root --ask-su-pass -m shell -a 'free -m' [HOSTGRUPPE]
#nach sudo passwort für skript fragen wenn become_method
ansible-playbook playbook1.yml --ask-become-pass

###############################################
---
- hosts: [HOSTGRUPPE]
  user: [USER]
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - shell: free -m

- name: Upgrade distribution
  apt: update_cache=yes upgrade=yes cache_valid_time=1800

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - fail2ban
    - ntp
    - unattended-upgrades
    - apt-listchanges
    
- name: Modify SSH-Config
  - lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PubkeyAuthentication'
      line: 'PubkeyAuthentication yes'
      owner: root
      group: root
      mode: 0400

- name: Restart ntp client
  action: service name=ntp state=restarted enabled=yes

- name: Stop Bluetooth
  action: service name=bluetooth state=stop enabled=no
