---
<<<<<<< HEAD
- hosts: assimilate
=======
- hosts: firstinstall
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4
  vars:
  - ansible_ssh_user: "{{ ssh_user }}"
  - ansible_ssh_pass: "{{ ssh_pass }}"
  - ssh_host_key_checking: false
  vars_prompt:
    - name: "ssh_user"
      prompt: "Connect user"
      private: no
    - name: "ssh_pass"
      prompt: "Connect password (leave empty if key placed)"
      private: yes

  tasks:
  - name: Check user
    command: grep "{{ ssh_user }}" /etc/passwd
    register: user_available
    ignore_errors: true
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  ignore_unreachable: yes
  roles:
    - user-ansible
