---
- name: install unattended-upgrades
  package:
    name: unattended-upgrades
    state: present

- name: install apt-listchanges
  package:
    name: apt-listchanges
    state: present

- name: Modify 20auto-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Modify 02periodic
  template:
    src: 02periodic.j2
    dest: /etc/apt/apt.conf.d/02periodic
    owner: root
    group: root
    mode: '0644'
    backup: yes
