---
- name: load vars
#  vars_prompt:
#    - name: "new_user"
#      prompt: "Which userto move?"
#      private: no
  include_vars:
    file: user.yml
    name: user

- name: Check home
  command: ls /home/pi
  register: home_available
  ignore_errors: true

- name: Check user
  command: grep "pi:x:1000" /etc/passwd
  register: user_available
  ignore_errors: true

- name: Check group
  command: grep "pi:x:1000" /etc/group
  register: group_available
  ignore_errors: true

- name: Change home to {{ user['username'] }}
  user:
    name: pi
    group: pi
    home: "/home/{{ user['username'] }}"
    move_home: yes
  when: home_available is succeeded

- name: Change user to {{ user['username'] }}
  shell: usermod --login {{ user['username'] }} pi
  when: user_available is succeeded

- name: Change group to {{ user['username'] }}
  shell: groupmod --new-name {{ user['username'] }} pi
  when: group_available is succeeded

- name: Set authorized key took from file
  authorized_key:
    user: "{{ user['username'] }}"
    state: present
    key: "{{ user['publickey'] }}"

