- name: Install packages
  package:
    name: samba
    state: present

- name: Create user {{ samba_user }}
  user:
    name: "{{ samba_user }}"
    create_home: no
    shell: "/bin/false"

- name: Get id of {{ samba_user }}
  shell: 'id -u {{ samba_user }}'
  register: samba_userid
  changed_when: false

- name: Create userdump of {{ samba_user }}
  copy:
    content: "{{ samba_user }}:{{ samba_userid.stdout }}:{{ samba_hash }}"
    dest: /etc/samba/smbpasswd
    force: yes
    owner: root
    group: root
    mode: '0600'
    backup: yes

- name: Import userdump of {{ samba_user }}
  shell: 'pdbedit -i smbpasswd -e tdbsam'

- name: Mod config
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
    validate: 'testparm -s %s'
  notify:
    - restart smbd
  tags: smb

- name: Get running and enabled
  service:
    name: smbd
    state: started
    enabled: yes
  tags: smb
