- name: Install packages
  package:
    name: ['python-apt', 'samba']
    state: latest
  when: samba_enabled | bool

- name: Create user {{ samba_user }}
  user:
    name: "{{ samba_user }}"
    create_home: no
    shell: "/bin/false"
  when: samba_enabled | bool

- name: Get id of {{ samba_user }}
  shell: 'id -u {{ samba_user }}'
  register: samba_userid
  changed_when: false
  when: samba_enabled | bool

- name: Create userdump of {{ samba_user }}
  copy:
    content: "{{ samba_user }}:{{ samba_userid.stdout }}:{{ samba_hash }}"
    dest: /etc/samba/smbpasswd
    force: yes
    owner: root
    group: root
    mode: '0600'
    backup: yes
  when: samba_enabled | bool

- name: Import userdump of {{ samba_user }}
  shell: 'pdbedit -i smbpasswd -e tdbsam'
  when: samba_enabled | bool

- name: Mod config
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
    validate: 'testparm -s %s'
  notify:
    - restart smbd
  tags: smb
  when: samba_enabled | bool
  register: samba_config
##TODO set permissions on dir with acls

- name: Get running and enabled
  service:
    name: smbd
    state: started
    enabled: yes
  tags: smb
  when: samba_enabled | bool and  samba_config is changed

#Firewall rules

#For Debian-based systems python-apt package must be installed on targeted hosts.
- name: Gather the package facts
  package_facts:
    manager: auto
  when: samba_enabled | bool

#Print installed packages for debug
#- name: Print the rpm package facts
#  debug:
#    var: ansible_facts.packages

##TODO rewok for if not installed
#- name: Check whether a package called is installed
#  command: /usr/sbin/ufw allow samba
#  debug:
#    msg: "{{ ansible_facts.packages['ufw'] | length }} versions of ufw are installed!"
#  when: "'ufw' in ansible_facts.packages"
