- name: Install packages
  package:
    name: samba
    state: present

- name: Create user {{ samba_user }}
  user:
    name: "{{ samba_user }}"
    create_home: no
    shell: "/bin/false"

- name: Mod config
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
    validate: 'testparm -s %s'
  notify:
    - restart smbd
  tags: smb

- name: Get running and enabled
  service:
    name: smbd
    state: started
    enabled: yes
  tags: smb

##TODO smbuseradd
# get smb userdatabase pdbedit -L -w
# import smb userdatabase pdbedit --import={FILE}
