- name: Mod config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify:
    - restart sshd
  tags: sshd

- name: Get running and enabled
  service:
    name: sshd
    state: started
    enabled: yes
  tags: sshd
