- name: Mod config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
<<<<<<< HEAD
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify:
    - restart sshd
  tags: sshd

- name: Get running and enabled
  service:
    name: sshd
    state: started
    enabled: yes
  tags: sshd
=======
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify:
    - restart ssh
  tags: ssh

- name: Get running and enabled
  service:
    name: ssh
    state: started
    enabled: yes
  tags: ssh
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4
