- name: create dir
  file:
    path: /docker/nginx
    state: directory
    mode: 0700

- name: Get old container name
  #cat if rep exit code is non-zero cats is zero
  shell: docker ps -a|grep -v Exited|awk '{print $NF}'|grep web_web|cat
  register: container_name_old
  changed_when: false

#- name: debug
#  debug:
#    msg: "Container: {{ container_name_old.stdout }}"

- name: Modify Docker Stack Nginx
  template:
    src: stack_nginx.yml.j2
    dest: /docker/stack_nginx.yml
    owner: root
    group: root
    mode: '0600'
    backup: yes
  when: (container_name_old.stdout == "")

- name: Use Nginx Config
  template:
    src: nginx.conf.j2
    dest: /docker/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Start Docker Stack Nginx
  shell: docker stack deploy -c /docker/stack_nginx.yml web
  changed_when: false
  when: (container_name_old.stdout == "")

- name: Wait for Container creation
  pause:
    seconds: 15

- name: Get new container name
  shell: docker ps -a|grep -v Exited|awk '{print $NF}'|grep web_web
  register: container_name_new
  changed_when: false
  when: (container_name_old.stdout == "")

- name: debug
  debug:
    msg: "Container: {{ container_name_new.stdout }}"
  when: (container_name_old.stdout == "")

###create php-frpm container from base image
- name: Create dockerfile
  template:
    src: dockerfile.j2
    dest: /docker/dockerfile
    owner: root
    group: root
    mode: '0600'
    backup: yes

- name: Compile dockerfile
  shell: docker build -t php7.2-mysql /docker/
###php7.0-fpm php7.0-gd php7.0-xml php7.0-zip php7.0-mysql imagemagick
