---
- name: Upgrade distribution
  apt: update_cache=yes upgrade=yes cache_valid_time=1800

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - fail2ban
    - ntp
    - unattended-upgrades
    - apt-listchanges
    
- name: Start ntp client
  action: service name=ntp state=started enabled=yes

#- name: Stop Bluetooth
#  action: service name=bluetooth state=stop enabled=no
