---
- name: Upgrade distribution
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
    autoclean: yes
    autoremove: yes

- name: Install packages
  apt: 
    name: ['fail2ban', 'ntp'] 
    state: latest
    
- name: Start ntp client
  action: service name=ntp state=started enabled=yes

#- name: Stop Bluetooth
#  action: service name=bluetooth state=stop enabled=no
