---
- name: Upgrade distribution
  apt:
    update_cache: yes
#    cache_valid_time: 3600
#    upgrade: dist
#    autoclean: yes
#    autoremove: yes

- name: workaround for dist-upgrade prompt
  shell: export DEBIAN_FRONTEND=noninteractive; apt-get -o Dpkg::Options::=\"--force-confnew\" --assume-yes dist-upgrade
#  shell: export DEBIAN_FRONTEND=noninteractive


- name: Install packages
  package:
    name: ['fail2ban', 'ntp', 'unattended-upgrades', 'apt-listchanges', 'iptables', 'ufw']
    state: latest

- name: Set 20auto-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Set 02periodic
  template:
    src: 02periodic.j2
    dest: /etc/apt/apt.conf.d/02periodic
    owner: root
    group: root
    mode: '0644'
    backup: yes

#Flush all iptables manually if needed:
#iptables-save | awk '/^[*]/ { print $1 }
#                     /^:[A-Z]+ [^-]/ { print $1 " ACCEPT" ; }
#                     /COMMIT/ { print $0; }' | iptables-restore; iptables-save;

#- name: Firststart ufw
#  shell: ufw allow ssh; ufw allow ntp; ufw enable

- name: Start and enable
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp

- name: Start and enable
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: fail2ban

- name: Start and enable
  service:
    name: ufw
    state: started
    enabled: yes
  tags: ufw
