---
- name: Upgrade distribution
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
    autoclean: yes
    autoremove: yes

- name: Install packages
  package:
    name: ['fail2ban', 'ntp', 'unattended-upgrades', 'apt-listchanges']
    state: latest

- name: Set 20auto-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Set 02periodic
  template:
    src: 02periodic.j2
    dest: /etc/apt/apt.conf.d/02periodic
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Set ntp running and enabled
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
