---
- name: Upgrade distribution
  apt:
    update_cache: yes
#    cache_valid_time: 3600
#    upgrade: dist
#    autoclean: yes
#    autoremove: yes

#- name: workaround for dist-upgrade prompt
#  shell: export DEBIAN_FRONTEND=noninteractive; apt-get -o Dpkg::Options::="--force-confnew" --assume-yes dist-upgrade
##  shell: export DEBIAN_FRONTEND=noninteractive


- name: Install packages
  package:
<<<<<<< HEAD
    name: ['fail2ban', 'ntp', 'unattended-upgrades', 'apt-listchanges', 'iptables', 'ufw', 'ntpdate']
=======
    name: ['fail2ban', 'ntp', 'unattended-upgrades', 'apt-listchanges', 'iptables', 'ufw']
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4
    state: latest

- name: Set 20auto-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Set 02periodic
  template:
    src: 02periodic.j2
    dest: /etc/apt/apt.conf.d/02periodic
    owner: root
    group: root
    mode: '0644'
    backup: yes

#Flush all iptables manually if needed:
#iptables-save | awk '/^[*]/ { print $1 }
#                     /^:[A-Z]+ [^-]/ { print $1 " ACCEPT" ; }
#                     /COMMIT/ { print $0; }' | iptables-restore; iptables-save;

- name: Allow ssh on ufw
  command: /usr/sbin/ufw allow ssh

<<<<<<< HEAD
- name: Set Timezone
  command: /usr/bin/timedatectl set-timezone "Europe/Berlin"

- name: Initial time sync
  command: /usr/sbin/ntpdate -u 0.debian.pool.ntp.org

=======
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4
- name: Start and enable ntp
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp

- name: Allow ntp on ufw
  command: /usr/sbin/ufw allow ntp

- name: Start and enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: fail2ban

##TODO
#- name: start ufw first time
#  command: /usr/sbin/ufw enable

- name: Start and enable ufw
  service:
    name: ufw
    state: started
    enabled: yes
  tags: ufw

##TODO set ntp servers + timezone
##TODO check rpi throttling /opt/vc/bin/vcgencmd get_throttled (0x50000 voltage 0x80000 heat)
