---
- name: Upgrade distribution
  apt:
    update_cache: yes
#    cache_valid_time: 3600
#    upgrade: dist
#    autoclean: yes
#    autoremove: yes

#sudo apt update --allow-releaseinfo-change
#Hit:1 http://archive.raspberrypi.org/debian buster InRelease
#Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
#Get:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
#Fetched 13.0 MB in 49s (264 kB/s)                                                                                                                                                                                                              
#Reading package lists... Done
#Building dependency tree       
#Reading state information... Done
#69 packages can be upgraded. Run 'apt list --upgradable' to see them.
#N: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'



#- name: workaround for dist-upgrade prompt
#  shell: export DEBIAN_FRONTEND=noninteractive; apt-get -o Dpkg::Options::="--force-confnew" --assume-yes dist-upgrade
##  shell: export DEBIAN_FRONTEND=noninteractive


- name: Install packages
  package:
    name: ['fail2ban', 'ntp', 'unattended-upgrades', 'apt-listchanges', 'iptables', 'ufw', 'ntpdate']
    state: latest

- name: Set 20auto-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Set 02periodic
  template:
    src: 02periodic.j2
    dest: /etc/apt/apt.conf.d/02periodic
    owner: root
    group: root
    mode: '0644'
    backup: yes

#Flush all iptables manually if needed:
#iptables-save | awk '/^[*]/ { print $1 }
#                     /^:[A-Z]+ [^-]/ { print $1 " ACCEPT" ; }
#                     /COMMIT/ { print $0; }' | iptables-restore; iptables-save;

- name: Allow ssh on ufw
  command: /usr/sbin/ufw allow ssh

- name: Set Timezone
  command: /usr/bin/timedatectl set-timezone "Europe/Berlin"

- name: Initial time sync
  command: /usr/sbin/ntpdate -u 0.debian.pool.ntp.org

- name: Start and enable ntp
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp

- name: Allow ntp on ufw
  command: /usr/sbin/ufw allow ntp

- name: Start and enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: fail2ban

##TODO
#- name: start ufw first time
#  command: /usr/sbin/ufw enable

- name: Start and enable ufw
  service:
    name: ufw
    state: started
    enabled: yes
  tags: ufw

##TODO set ntp servers + timezone
##TODO check rpi throttling /opt/vc/bin/vcgencmd get_throttled (0x50000 voltage 0x80000 heat)
