---
##TODO make unwritable if not mounted
- name: Create dir
  file:
    path: "{{ mounts_path }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  when: mounts_enabled | bool

- name: Mount up device by UUID
  mount:
    path: "{{ mounts_path }}"
    src: UUID="{{ mounts_uuid }}"
    fstype: ext4
    opts: defaults,nofail
    state: mounted
  when: mounts_enabled | bool
