---
##TODO make unwritable if not mounted
##TODO chown -R rslsync:rslsync /data;find /data -type d -exec chmod 755 {} \;;find /data -type f -exec chmod 644 {} \;;setfacl -R -m u:nasreader:rwX /data;setfacl -R -d -m u:nasreader:rwX /data
- name: Create dir
  file:
    path: "{{ mounts_path }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  when: mounts_enabled | bool

- name: Mount up device by UUID
  mount:
    path: "{{ mounts_path }}"
    src: UUID="{{ mounts_uuid }}"
    fstype: xfs
    opts: defaults,nofail,noatime
    state: mounted
  when: mounts_enabled | bool
