---
- name: Install packages
  package:
    name: ['tor']
    state: latest

- name: Put directory
  file:
    path: /var/lib/tor/hidden_service
    state: directory
    owner: debian-tor
    group: debian-tor
    mode: 0700

- name: Mod tor config
  template:
    src: torrc.j2
    dest: /etc/tor/torrc
    backup: yes
  notify:
    - restart tor
  tags: tor

- name: Start and enable
  service:
    name: tor
    state: started
    enabled: yes
  tags: tor

##TODO iptables -A OUTPUT -j ACCEPT -m owner --uid-owner debian-tor
