---
#script for creating ansible user and changing root pass
- name: Load variables
  include_vars:
    file: password.yml
    name: password_ansible

- name: Create user {{ password_ansible['username'] }}
  user:
    name: "{{ password_ansible['username'] }}"
    password: "{{ password_ansible['ansible_pass'] }}"
    create_home: yes
    skeleton: "/etc/skel"
    shell: "/bin/bash"
    groups: sudo
    append: yes

- name: Mod root
  user:
    name: root
    password: "{{ password_ansible['root_pass'] }}"

- name: Set authorized key
  authorized_key:
    user: "{{ password_ansible['username'] }}"
    state: present
##TODO use key from /etc/ansibble/privatekey/id_rsa.pub
    key: "{{ password_ansible['publickey'] }}"

- name: Enable key authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: "PubkeyAuthentication yes"
    state: present
  register: sshd_config

- name: Restart ssh
  shell: sleep 3; systemctl restart sshd
  async: 1
  poll: 0
  when: sshd_config is changed

- name: Delete sudo all all
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%sudo'
    state: absent
