---
#script for creating ansible user and changing root pass
#- name: Load variables
#  include_vars:
#    file: password.yml
#    name: password_ansible


- name: Create user {{ ansible_inventory_username | default('ansible') }}
  user:
    name: "{{ ansible_inventory_username | default('ansible') }}"
    password: "{{ ansible_pass }}"
    create_home: yes
    skeleton: "/etc/skel"
    shell: "/bin/bash"
    groups: sudo
    append: yes

- name: Mod root
  user:
    name: root
    password: "{{ root_pass }}"
  when: root_pass is defined

- name: Set authorized key
  authorized_key:
    user: "{{ ansible_inventory_username | default('ansible') }}"
    state: present
    key: "{{ pubkey_ansible | default('ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgiqLqpbtnajveGut0MVeqtG9v/GDTwUbY98Btdb9G9EUWiXJOXcXccukKoZ5I4iFajENIzxNEIEfqA7dcgwkwBwDS8I5o+oGvCGue3k8ihq9K1EKw3f404CgUCYG5dhQBqLJm5zjuuKMdnsREGe8PCmJtx0pZrLKphds58YGdYt651PCEq+/DCnvoKJVSSnEwCPKqFB6f2PFKlsjnI40CLQP2qe+ugmHre/ndFMo5hxk/s5WXnIKL5JMMfdrfC4xM8mUYuyMaWmGquh2s+bZWRnjfjrlGUsOl4KgE7nZtWDaWTalvTAEjuM3l2JXLOy3KikzspVQQIBTO4bht8UVt default@default')}}"

- name: Enable key authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: "PubkeyAuthentication yes"
    state: present
  register: sshd_config

#checks

- name: Get old user
  shell: 'id -nu 1000'
  register: user_old
  changed_when: false

#- name: debug
#  debug:
#    msg: "User: {{ user_old.stdout }}"

- name: Get home
  command: ls /home/"{{ user_old.stdout }}"
  register: home_available
  ignore_errors: true
  changed_when: false

- name: Get user
  command: grep "{{ user_old.stdout }}" /etc/passwd
  register: user_available
  ignore_errors: true
  changed_when: false

- name: Get group
  command: grep "{{ user_old.stdout }}" /etc/group
  register: group_available
  ignore_errors: true
  changed_when: false

#actions

##TODO add new user and then deactivate old user after he is logged off with shell script
#- name: Mod user home for {{ user['username'] }}
#  user:
#    name: "{{ user_old.stdout }}"
#    group: "{{ user_old.stdout }}"
#    home: "/home/{{ user['username'] }}"
#    move_home: yes
#  when: (user_old.stdout != user['username'])

#- name: Mod user name for {{ user['username'] }}
#  shell: /usr/sbin/usermod --login {{ user['username'] }} {{ user_old.stdout }}
#  when: (user_old.stdout != user['username'])

#- name: Mod user group for {{ user['username'] }}
#  shell: /usr/sbin/groupmod --new-name {{ user['username'] }} {{ user_old.stdout }}
#  when: (user_old.stdout != user['username'])

- name: Create user {{ username_default | default('default-user') }}
  user:
    name: "{{ username_default | default('default-user') }}"
    create_home: yes
    skeleton: "/etc/skel"
    shell: "/bin/bash"
    groups: sudo
    append: yes

- name: Set authorized key
  authorized_key:
    user: "{{ username_default | default('default-user') }}"
    state: present
    key: "{{ publickey_default | default('ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgiqLqpbtnajveGut0MVeqtG9v/GDTwUbY98Btdb9G9EUWiXJOXcXccukKoZ5I4iFajENIzxNEIEfqA7dcgwkwBwDS8I5o+oGvCGue3k8ihq9K1EKw3f404CgUCYG5dhQBqLJm5zjuuKMdnsREGe8PCmJtx0pZrLKphds58YGdYt651PCEq+/DCnvoKJVSSnEwCPKqFB6f2PFKlsjnI40CLQP2qe+ugmHre/ndFMo5hxk/s5WXnIKL5JMMfdrfC4xM8mUYuyMaWmGquh2s+bZWRnjfjrlGUsOl4KgE7nZtWDaWTalvTAEjuM3l2JXLOy3KikzspVQQIBTO4bht8UVt default@default') }}"
#till here

- name: Restart ssh
  shell: sleep 3; systemctl restart sshd
  async: 1
  poll: 0
  when: sshd_config is changed

- name: Delete sudo all all
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%sudo'
    state: absent
