---
- name: Install packages
  apt: 
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common'] 
    state: latest

- name: Add docker repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repo
  shell: echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

- name: Reload Repos
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    update_cache: yes
