---
- name: Install packages
  package:
    name: ['apt-transport-https', 'ca-certificates', 'software-properties-common']
    state: latest

- name: Create repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: Add docker repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Install packages
  #currently 2018-07-07 not working package error
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    install_recommends: no

- name: Set directory
  file:
    path: /docker
    state: directory
    mode: 0700
#docker node ls|echo $?##if 1 still no swarm node if 0 swarm node
#- name: Create Docker Swarm##TODO run oly once
#  shell: docker swarm init
#  changed_when: false
