---
- name: Install packages
  apt: 
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common'] 
    state: latest

- name: Add docker repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Register debian_ver
  shell: lsb_release -cs
  register: debian_ver
  changed_when: false

- name: Set debian release for docker
  set_fact:
    debian_release: "{{ debian_ver.stdout_lines }}"

#- name: Display all variables/facts known for a host
#  debug:
#    var: hostvars[inventory_hostname]
#    verbosity: 4

- name: Add Docker Repo
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: docker

- name: Reload Repos
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    update_cache: yes

- name: Create Dir
  file:
    path: /docker
    state: directory
    mode: 0700
#docker node ls|echo $?##if 1 still no swarm node if 0 swarm node
#- name: Create Docker Swarm##TODO run oly once
#  shell: docker swarm init
#  changed_when: false
