---
- name: Check architecture of host
  shell: dpkg --print-architecture
  register: architecture
  changed_when: architecture.rc == 1
<<<<<<< HEAD
  when: rslsync_enabled | bool
=======
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4

- name: Set repo key
  apt_key:
    url: https://linux-packages.resilio.com/resilio-sync/key.asc
    state: present
<<<<<<< HEAD
  when: rslsync_enabled | bool
=======
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4

- name: Create repo for {{ architecture.stdout }}
  apt_repository:
    repo: deb [arch={{ architecture.stdout }}] http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
    state: present
    filename: resilio-sync
    update_cache: yes
<<<<<<< HEAD
  when: rslsync_enabled | bool

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "resilio-sync"
    - "acl"
  when: rslsync_enabled | bool

- name: create dirs
  file: 
    path: "{{ item.value.folder }}"
    state: directory
    mode: 755
    owner: rslsync
    group: rslsync
  with_dict: "{{ resilio_folders }}"
  when: rslsync_enabled | bool

- name: create default dir
  file:
    path: "{{ resilio_storage_path }}"
    state: directory
    mode: 755
    owner: rslsync
    group: rslsync
  when: rslsync_enabled | bool

#- name: set default ACL
#  acl:
#    path: "{{ resilio_storage_path }}"
#    recursive: yes
#    entity: rslsync
#    etype: user
#    permissions: rwX
#    default: yes
#    state: present
#  when: rslsync_enabled | bool

#- name: set ACL
#  acl:
#    path: "{{ resilio_storage_path }}"
#    recursive: yes
#    entity: rslsync
#    etype: user
#    permissions: rwX
#    state: present
#  when: rslsync_enabled | bool

#- name: set default ACL
#  acl:
#    path: "{{ item.value.folder }}"
#    recursive: yes
#    entity: rslsync
#    etype: user
#    permissions: rwX
#    default: yes
#    state: present
#  with_dict: "{{ resilio_folders }}"
#  when: rslsync_enabled | bool

#- name: set ACL
#  acl:
#    path: "{{ item.value.folder }}"
#    recursive: yes
#    entity: rslsync
#    etype: user
#    permissions: rwX
#    state: present
#  with_dict: "{{ resilio_folders }}"
#  when: rslsync_enabled | bool

=======

- name: Install packages
  package:
    name: resilio-sync
    state: present

##TODO change log dir to /var/log/resilio-sync
##TODO set dir permission that gets synced
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4
- name: Mod config
  template:
    src: config.json.j2
    dest: /etc/resilio-sync/config.json
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - restart rslsync
  tags: resilio-sync
<<<<<<< HEAD
  when: rslsync_enabled | bool
=======
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4

- name: Make sure a service is running
  systemd:
    state: started
    name: resilio-sync
    enabled: yes
<<<<<<< HEAD
  when: rslsync_enabled | bool
=======
>>>>>>> 1b90abf07db7721c59eca7b4383d1a727f36a8a4
