---
#- name: load vars
#  include_vars:
#    file: urls.yml
#    name: urls

- name: list
  vars:
    url_all:
      host1:
        url_s: example.com
        url_d: test.com
      host2:
        url_s: example2.com
        url_d: test2.com

    
- name: debug
  debug: msg="item"
  with_list: "{{lookup('subelement', url_all, 'url_s')}}"


#- name: debug
#  debug: msg={{urls}}

#- name: debug2
#  debug: msg={{ urls['url_all'] }}

#- name: debug3
#  debug: msg={{ urls['url_all']['url_s'] }}

- name: create vhosts
  template:
    src: vhost_reverseproxy.j2
    dest: "/etc/nginx/sites-available/{{ item }}.vhost"
    owner: root
    group: root
    mode: '0644'
    backup: yes
#  with_items: "{{ urls['url_source'] }}"
  with_items: "{{ urls['url_all']['host1']['url_s'] }}"








- name: customize source url
  replace:
    dest: "/etc/nginx/sites-available/{{ item }}.vhost"
    regexp: 'URL_SOURCE'
    replace: "{{ urls['url_source'] }}"
  with_items: "{{ urls['url_all']['url_s'] }}"

- name: customize destination url
  replace:
    dest: "/etc/nginx/sites-available/{{ item }}.vhost"
    regexp: 'URL_DESTINATION'
    replace: "{{ urls['url_destination'] }}"
  with_items: "{{ urls['url_all']['url_s'] }}"
